Update invoice_ai_ui.py
fixed some format / indentn error after the pkg was replaced

File "/mount/src/invoiceprocessing/invoice_ai_ui.py", line 31
      st.image(image, caption="Invoice Preview", use_column_width=True)
     ^
IndentationError: unexpected indent